"""
ATT&CK Mapping Builder and Navigator Layer Reporter.
Provides utilities for building ATT&CK mappings from detection findings.
"""

from __future__ import annotations
from typing import List
from dataclasses import dataclass

from .models import Domain, ATTACKMapping
from .index import ATTACKIndex


@dataclass
class ATTACKMappingBuilder:
    """Builds ATTACKMapping objects from technique IDs using an ATTACKIndex."""

    index: ATTACKIndex

    def build(self, technique_id: str, confidence: float = 0.5) -> ATTACKMapping:
        """Build a single ATTACKMapping from a technique ID."""
        tech = self.index.get(technique_id)
        if not tech:
            return ATTACKMapping(
                tactic_id="",
                tactic_name="",
                technique_id=technique_id,
                technique_name="Unknown",
                subtechnique_id=None,
                subtechnique_name=None,
                domain=Domain.ENTERPRISE,
                confidence=confidence,
            )

        tactic_id = tech.tactic_ids[0] if tech.tactic_ids else ""
        tactic = self.index._tactics.get(tactic_id)
        tactic_name = tactic.name if tactic else ""

        if tech.is_subtechnique:
            # Get parent technique name
            parent_id = (
                tech.attack_id.split(".")[0]
                if "." in tech.attack_id
                else tech.parent_id
            )
            parent_tech = self.index.get(parent_id)
            parent_name = parent_tech.name if parent_tech else tech.name

            return ATTACKMapping(
                tactic_id=tactic_id,
                tactic_name=tactic_name,
                technique_id=parent_id,
                technique_name=parent_name,
                subtechnique_id=tech.attack_id,
                subtechnique_name=tech.name,
                domain=tech.domain,
                confidence=confidence,
                data_sources=tech.data_sources,
                platforms=tech.platforms,
                url=tech.url,
            )
        else:
            return ATTACKMapping(
                tactic_id=tactic_id,
                tactic_name=tactic_name,
                technique_id=tech.attack_id,
                technique_name=tech.name,
                subtechnique_id=None,
                subtechnique_name=None,
                domain=tech.domain,
                confidence=confidence,
                data_sources=tech.data_sources,
                platforms=tech.platforms,
                url=tech.url,
            )

    def build_many(
        self, technique_ids: List[str], confidence: float = 0.5
    ) -> List[ATTACKMapping]:
        """Build multiple ATTACKMappings from a list of technique IDs."""
        return [self.build(tid, confidence) for tid in technique_ids]


class NavigatorLayerReporter:
    """Outputs ATT&CK Navigator layer JSON v4.5."""

    def generate(self, repo_name: str, mappings: List[ATTACKMapping]) -> str:
        import json

        techniques = []
        seen = set()
        for m in mappings:
            if m is None:
                continue
            tid = m.subtechnique_id or m.technique_id
            if tid in seen:
                continue
            seen.add(tid)
            techniques.append(
                {
                    "techniqueID": tid,
                    "tactic": m.tactic_id,
                    "score": int(m.confidence * 100),
                    "comment": f"{repo_name} detection \u2014 ATT&CK v19",
                    "enabled": True,
                    "color": "",
                    "metadata": [{"name": "repo", "value": repo_name}],
                }
            )

        layer = {
            "name": f"{repo_name} ATT&CK v19 Coverage",
            "versions": {"attack": "19", "navigator": "4.9", "layer": "4.5"},
            "domain": "enterprise-attack",
            "description": f"Generated by {repo_name} ATT&CK enricher. v19: TA0005=Stealth (renamed from Defense Evasion); TA0112=Defense Impairment (new).",
            "filters": {
                "platforms": [
                    "Windows",
                    "macOS",
                    "Linux",
                    "AWS",
                    "Azure",
                    "GCP",
                    "Containers",
                    "Network",
                    "SaaS",
                    "IaaS",
                    "Office 365",
                    "Google Workspace",
                ]
            },
            "sorting": 3,
            "layout": {
                "layout": "side",
                "showAggregateScores": True,
                "countUnscored": False,
                "aggregateFunction": "max",
            },
            "hideDisabled": False,
            "techniques": techniques,
            "gradient": {
                "colors": ["#ffffff", "#ff6666"],
                "minValue": 0,
                "maxValue": 100,
            },
            "legendItems": [{"label": "Detection coverage", "color": "#ff6666"}],
            "tacticRowBackground": "#dddddd",
            "selectTechniquesAcrossTactics": True,
            "selectSubtechniquesWithParent": False,
            "metadata": [
                {"name": "attack_version", "value": "19"},
                {"name": "generated_by", "value": repo_name},
                {
                    "name": "tactic_note",
                    "value": "TA0005=Stealth (renamed from Defense Evasion); TA0112=Defense Impairment (new)",
                },
            ],
        }
        return json.dumps(layer, indent=2)
